on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n vtsc123 -g vtsc1239b84-rg --location "Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n vtsc123 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n vtsc123 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n vtsc123 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: vtsc123.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockrfile" -t vtsc123.azurecr.io/house:${{ github.sha }} --label dockerfile-path=Dockrfile
        docker push vtsc123.azurecr.io/house:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_house_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep housead4a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace housead4a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: housead4a
        container-registry-url: vtsc123.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: housedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: housead4a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          vtsc123.azurecr.io/house:${{ github.sha }}
        imagepullsecrets: |
          housedockerauth   
